[theme]
primaryColor = "#1E90FF"                # Dodger Blue (finance/trading accent)
backgroundColor = "#0E1117"             # Deep Charcoal (modern trading UIs)
secondaryBackgroundColor = "#23272F"    # Slightly lighter for panels/widgets
textColor = "#F5F6FA"                   # Very light gray for high contrast
font = "sans serif"                     # Clean, readable font